fos_rest:
    view:
        view_response_listener: 'force'
        formats:
            json: true
    format_listener:
        rules:
        - { path: '^/', priorities: ['json'], fallback_format: json, prefer_extension: false }
    body_converter:
        enabled: true
        validate: true
    param_fetcher_listener: true
    serializer:
        serialize_null: true